routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ListOfRoomsController@create');

// Route::get('/', function () {
//     return view('sample');
// });

Auth::routes(['register' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/admin',function(){
    return view('layouts.admin');
});

// Room and booking
Route::resource('room', 'RoomController');
Route::get('allinreserved','ReservationController@reserved');
Route::get('bookedclient','ReservationController@booked');
Route::resource('reservation', 'ReservationController', ['except' => 'show']);
Route::get('reservation/{id}/{checkIn}/{checkOut}', 'ReservationController@show')->name('reservation.show');
Route::post('room/getRoom', 'RoomController@getRoomDetails')->name('room.getRoomDetails');
Route::get('room/getDetails/{id}', 'RoomController@getRoomDetailsId');
Route::get('room/check-availability/{check_in}/{check_out}', 'RoomController@checkAvailable')->name('room.check');
Route::get('datepicker', function(){
    return view('room.check');
});
Route::get('/payment/success', 'ReservationController@paymentSuccess');
Route::get('/payment/refund', 'ReservationController@refundTransaction');
Route::resource('insert', 'InsertController');
Route::post('paypal/notify', 'ReservationController@notify');
Route::post('tourPackage','ReservationController@tourPackageData');


//List of Rooms
Route::resource('list','ListOfRoomsController');
Route::get('session/destroyer', 'ReservationController@sessionDestroy');
Route::get('getDates/{id}', 'ReservationController@getDates');
Route::get('/getAvaiableRooms/{checkIn}/{checkOut}', 'RoomController@getAvailableRooms');
Route::get('/updateCheckStatus/{id}/{check}','ReservationController@updateCheckinStatus');
Route::get('contactUs','API\ContactUsController@store');

//get all Package
Route::get('getPackageDates/{id}', 'ReservationController@PackageDates');
Route::get('getAvailableRooms/{id}','ReservationController@AvailableRoom');
Route::get('getbookRoom/{id}','ReservationController@bookedRoom');
//search
Route::post('searchReservation','ReservationController@searchforResearved');
Route::get('reserveDetails/{id}','ReservationController@detialsofResearved');



Route::get('roomDetails/{id}','ListOfRoomsController@roomDetails');
Route::get('{path}','HomeController@index')->where('path','([A-z\d\/_.]+)?');
Route::get('/test1', function(){
    return \App\OtherRoomPhoto::all();
});

Route::post('quotation-Page','QuotationController@send');



//catering
Route::get('catering-Service', function(){
    return view('content.catering');
});

// tour package
Route::get('tour-Package', function(){
    $package = \App\Package::all();
    return view('content.tourPackage',compact('package'));
});

//ajax details
Route::get('tourPackage-Modal/{id}','RoomDetailsController@packageDetails');
Route::get('Room-Modal/{id}','RoomDetailsController@roomDetails');

// van package
Route::get('van-transport', function(){
    return view('content.vanTransport');
});

// FUNCTIONS & EVENTS (quotation)
Route::get('functions-quotation', function(){
    return view('content.quotation');
});

//press release
 Route::get('press-release', function(){
    return view('content.pressRelease');
});

// locale (attraction)
Route::get('locale-attraction', function(){
    return view('content.localAttraction');
});

// locale (delicacies)
Route::get('locale-delicacies', function(){
    return view('content.localDelicacies');
});
//quotation
Route::get('quotations', function(){
    return view('content.quotation');
});
// locale (events)
Route::get('locale-events', function(){
    return view('content.localEvents');
});

// terms
Route::get('terms', function(){
    $terms = \App\terms::all();
    return view('content.terms',compact('terms'));
});

//garden-resort
Route::get('garden-resort', function(){
    $amenities = \App\Amenities::where('branch_id',1)->get();
    $room = \App\Room::with('room_amenities','room_details')->where('branch_id',1)->get();
    $guestRequest = \App\ExtraRequest::all();

    return view('content.gardenResort', compact('amenities','room','guestRequest'));
});

//beach-resort
Route::get('beach-resort', function(){
    $amenities = \App\Amenities::where('branch_id',2)->get();
    $room = \App\Room::with('room_amenities','room_details')->where('branch_id',2)->get();
    $guestRequest = \App\ExtraRequest::all();
    return view('content.beachResort', compact('amenities','room','guestRequest'));
});


Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    return "Cache is cleared";
});

//payment
Route::get('PackagePayment',function(){
    return view('payment.tourPackagePayment');
});

resources/views/modal/TermsAndConditionModal.blade.php
<!-- Modal -->
<div class="modal fade" href="/term" id="TermsAndConditionModal" tabindex="-1" role="dialog" aria-labelledby="TermsAndConditionModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
       
        <div class="modal-body">
            <h1 class="text-center">Terms and Condtion </h1>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn text-white acceptTerm" style="background-color:indigo" data-dismiss="modal">Accept</button>
        </div>
      </div>
    </div>
  </div>

resources/views/modal/bookModal.blade.php
 <!-- Modal -->
 <form action="{{ route('reservation.store') }}" method="POST" >
    @csrf
   <div class="modal fade" id="bookNowModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
       <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
       <div class="modal-content">
           <div class="modal-header text-white" style="background-image: linear-gradient(to right, #410064 , violet);">
               <h5 class="modal-title" id="exampleModalLongTitle">Confirm Your Reservation</h5>
               <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                   <span aria-hidden="true">&times;</span>
               </button>
           </div>
           <div class="modal-body p-0">
               <div class="text-center modalDate p-4">
                   {{-- Booking Details --}}
                   {{ Form::hidden('dates', '', ['id' => 'booking_dates']) }}
                   {{ Form::hidden('room_detail_id', $rooms->room_details->first()->id, ['id' => 'room_id']) }}
                   {{ Form::hidden('total_cost', old('total_cost'), ['id'=>'total_cost']) }}
                   {{ Form::hidden('charges', '', ['id'=>'charges']) }}

                   
                   {{-- User Details --}}
                   {{ Form::hidden('firstname', '', ['id'=>'formFirstName']) }}
                   {{ Form::hidden('lastname', '', ['id'=>'formLastName']) }}
                   {{ Form::hidden('contact_number', '', ['id'=>'formContactNumber']) }}
                   {{ Form::hidden('email', '', ['id'=>'formEmail']) }}
                   {{ Form::hidden('nationality', '', ['id'=>'formNationality']) }}
                   {{ Form::hidden('special_request', '', ['id'=>'formSpecialRequest']) }}
                   {{ Form::hidden('night', '', ['id'=>'night']) }}
                   {{ Form::hidden('priceNight', $rooms->price, ['id'=>'priceNight'])  }}
                   {{ Form::hidden('paymentMethod', '', ['id'=>'formpaymentofMethod'])  }}

                   <i class="fas fa-calendar-alt"></i>
                   {{-- June 06 --}}{{\Carbon\Carbon::parse($checkIn)->format('M d')}}
                   <i class="fas fa-angle-right ml-2 mr-2"></i>
                   <i class="fas fa-calendar-alt"></i>
                   {{-- June 10 --}}{{\Carbon\Carbon::parse($checkOut)->format('M d')}}
                   <i class="fas fa-angle-right ml-2 mr-2"></i>
                   <i class="fas fa-moon"></i>
                   <span class="noOfNights"></span> &nbsp;Nights                        
               </div>
               <div class="row p-2">

                   {{-- Customer Details --}}
                   <div class="col-md-6">
                       <div class="text-center p-3 h4 font-weight-bold">
                            Your Details
                       </div>
                       <div class="pl-3 pr-3 font-weight-bold">
                          Name:
                       </div>
                       <div class="pl-5 pr-3 font-weight-bold" style="font-size:18px;color:#4B0082">
                           <span class="text-capitalize" id="displayFname"></span>
                           <span class="text-capitalize" id="displayLname"></span>
                       </div>
                       <div class="pl-3 pr-3 font-weight-bold">
                          Contact #:
                       </div>
                       <div class="pl-5 pr-3 font-weight-bold" style="font-size:18px;color:#4B0082">
                          <span id="displayContact"></span>
                       </div>
                       <div class="pl-3 pr-3 font-weight-bold">
                          Email:
                       </div>
                       <div class="pl-5 pr-3 font-weight-bold" style="font-size:18px;color:#4B0082">
                          <span id="displayEmail"></span>
                       </div>
                       <div class="pl-3 pr-3 font-weight-bold">
                        Nationality:
                        </div>
                        <div class="pl-5 pr-3 font-weight-bold" style="font-size:18px;color:#4B0082">
                            <span id="displayNationality"></span>
                        </div>
                        <div class="pl-3 pr-3 font-weight-bold">
                            Mode of Payment:
                        </div>
                        <div class="pl-5 pr-3 font-weight-bold text-justify" style="font-size:18px;color:#4B0082">
                                <span id="displaypaymentMethod">%</span>
                        </div>  
                       <div class="pl-3 pr-3 font-weight-bold">
                          Special Request:
                       </div>
                       <div class="pl-5 pr-3 font-weight-bold text-justify" style="font-size:18px;color:#4B0082">
                               <span id="displayRequest"></span>
                       </div>  
                     
                       
                   </div>


                   {{-- Reservation Details --}}
                   <div class="col-md-6 reservation_detials" style="border-left: #E1D8CF solid 1px;">
                       <div class="text-center p-3 h4 font-weight-bold">
                            Reservation Details
                       </div>
                       <div class="modalDate pl-1 text-dark">
                               <span class="font-weight-bold">Select Room/Rates</span> 
                           </div>
                           <div class="pl-2 pr-4 font-weight-bold">
                               <span style="color:indigo">{{ $rooms->type }} #{{ $rooms->room_details->first()->room_no }}</span><span class="float-right"><span style="color:#61B361">&#8369;{{ $rooms->price }}</span>/Night</span>
                           </div>
                           <div class="pl-2 pr-4 font-weight-bold" style="font-style:italic;">
                               Not refundable
                           </div>
                          
                           <div>
                               <span class="pl-2 pr-4 font-weight-bold" style="font-style:italic;">Tax Inclusive</span>
                           </div>
                           <div class="mb-2">
                               <span class="pl-2 pr-4 font-weight-bold">Sub Total </span><span class="float-right pr-4" style="color:#61B361 !important;font-weight:bold;font-size:20px;" id="displayprice"></span>
                               <span class="float-right" style="color:#61B361 !important;font-weight:bold;font-size:20px;">&#8369; </span>
                           </div>
                           <br>
                           <br>
                           <hr>
                           
                           <div class="pl-2 pr-4 font-weight-bold" style="font-style:italic;">
                            Additional Charge(Request) <span class="float-right price " style="color:#61B361 !important;font-weight:bold;font-size:15px;" id="requestPrice">0</span> 
                            <span class="float-right " style="color:#61B361 !important;font-weight:bold;font-size:15px;">&#8369;</span> 
                            </div>
                           <div class="pl-2 pr-4 font-weight-bold" style="font-style:italic;">
                               <span class="pr-4 font-weight-bold">Total Amount</span><span class="float-right price" style="color:#61B361 !important;font-weight:bold;font-size:25px;" id="displayTotal"></span> 
                               <span class="float-right " style="color:#61B361 !important;font-weight:bold;font-size:25px;">&#8369; </span> 
                           </div>
                   </div>

                   <div class="col-12 m-2 ">
                            <input type="checkbox" name="" id="termS"> I hereby agree to the <button type="button"  data-toggle="modal" data-target="#TermsAndConditionModal">Terms and Condition</a> 
                   </div>
               </div>
              
           </div>
           <div class="modal-footer">
           <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
           <button type="submit" class="btn text-white payBtn"   style="background-color:indigo" disabled>Confirm and Pay</button>
           </div>
       </div>
       </div>
   </div>
</form>
   {{-- end modal --}}
   <!-- Modal -->
<div class="modal fade" id="TermsAndConditionModal" tabindex="-1" role="dialog" aria-labelledby="TermsAndConditionModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered " role="document">
      <div class="modal-content bg-info">    
        <div class="modal-body text-center">
            <h1 class="text-center">Terms and Condition </h1><hr>
            50% downpayment, 50% full payment upon arrival<br>
            No refund
  
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn text-white acceptTerm bg-success" data-dismiss="modal">Accept</button>
        </div>
      </div>
    </div>
  </div>
  

resources/views/modal/gardenResortModal.blade.php
<!-- modal use for dynamic -->
  <!-- Garden View Room Modal -->
  <div class="modal fade " id="gardenViewRoom" tabindex="-1"  role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" >
    <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered modal-lg" role="document" style="-webkit-box-shadow: -1px 2px 36px 4px rgba(222,98,222,0.49);
    -moz-box-shadow: -1px 2px 36px 4px rgba(222,98,222,0.49);
    box-shadow: -1px 2px 36px 4px rgba(222,98,222,0.49);">
      {{-- start of form --}}

        <div class="modal-content w-100">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">name</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body mb-5">
        <form action="{{ route('reservation.store') }}" method="POST" id="gardenRoom">
          @csrf
            <div class="px-5">
              
            <img style="height:400px;" class="w-100 image" src="" alt="">
              <h3 class="mt-2 text-bold">Room Details</h3>
              <p style="font-size:16px;">A very good place to be.</p>
           
        
                <div style="font-size:18px;">
                <i class="fa fa-home" aria-hidden="true"></i><span class="text-bold"> Room No: #</span><span id="room_no"> </span><br>
                </div>
          
              <div style="font-size:18px;">
              <i class="fa fa-bed" aria-hidden="true"></i><span class="text-bold">  No of Bed: #</span>
                    <ul>
                        <li><span id="queenBed"></span> Queen Bed/s</li>
                        <li><span id="singleBed"></span> Single Bed/s </li>  
                    </ul>
              </div>
              <div style="font-size:18px;">
                <i class="fa fa-male" aria-hidden="true"></i><span class="text-bold"> Max No. of Guest/s: </span><span id="guest"></span><br>
              </div>

              <div style="font-size:18px;">
                <i class="fa fa-smile-o" aria-hidden="true"></i><span class="text-bold"> Inclusion:</span>
                <span id="amenities"></span>
                <br>
              </div>
              <div style="font-size:18px;">
              <i class="fas fa-money-bill-alt    "></i><span class="text-bold"> Price/Nights: </span><span id="price"></span> Php<br>
             
              </div>
              <div style="font-size:18px;">
              <i class="fa fa-info-circle" aria-hidden="true"></i></i><span class="text-bold"> Room Description: </span><span id="description"></span><br>
              </div>
            </div>
            <br>
      
               {{-- hidden form input --}}
               {{ Form::hidden('total_cost','', ['id'=>'roomPrice','class' => 'form-control '])  }}
               {{ Form::hidden('room_detail_id','', ['id'=>'room_details_id','class' => 'form-control'])  }}
               {{ Form::hidden('room_id','', ['id'=>'roomID','class' => 'form-control'])  }}
              {{ form::hidden('roomPrice','', ['id'=> 'priceperNight','class'=>'form-control']) }}
           
              <div class="border border-dark p-2 " > 

                <p class="h4 m-4 text-center text-bold border border-dark bg-dark ">Reservation Details</p>
                      <div class="form-row">
                        <div class="col-8">
                          <label for="">Check In - Check Out</label>
                          <input type="text" class="form-control dates" id="roomDate"  name="dates">
                        </div>
                        <div class="col-4">
                          <label for="">No. of night</label>
                          <input type="text" class="form-control nights" name="night"  readonly>
                        </div>
                      </div>
                  
                      <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="ClientName" class="col-form-label">First Name:</label>
                            {{ Form::text('firstname', '', ['id'=>'formFirstName','class' => 'form-control']) }}
                        </div>
                        <div class="form-group col-md-4">
                            <label for="ClientName" class="col-form-label">Last Name:</label>
                            {{ Form::text('lastname', '', ['id'=>'formLastName','class' => 'form-control']) }}
                        </div>
                        <div class="form-group col-md-4">
                            <label for="ClientName" class="col-form-label">Email:</label>
                            {{ Form::text('email', '', ['id'=>'formEmail','class' => 'form-control']) }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="ClientCelNo" class="col-form-label">CELLULAR NO.:</label>
                            {{ Form::text('contact_number', '', ['id'=>'formContactNumber','class' => 'form-control']) }}
                        </div>
        
                        <div class="form-group col-md-6">
                            <label for="ClientNatinality" class="col-form-label">NATIONALITY:</label>
                            {{ Form::text('nationality', '', ['id'=>'formNationality','class' => 'form-control']) }}
                        </div>
                    </div>
        
                    <div class="row py-2 mx-auto">
                        <div class="form-group col-md-6">
                                <label  class=" col-form-label">Payment Type:</label>
                                {{ Form::select('paymentMethod', ['Full Payment' => 'Full Payment', 'Partial Payment' => 'Partial Payment'], 'S',['class' => 'form-control paymenttype']) }}
                              
                        </div>
        
                        <div class="form-group col-md-6">
                            <label for="ClientNatinality" class="col-form-label">Subtotal Price:</label>
                            <input type="text" class="form-control Totalprice"  id="cost" readonly >
                        </div>
                    </div>

                    <div class="form-group md-form ">
                                    <label for="request" class="font-weight-bold text-center   w-100">Special Request:</label>
                                    {{ Form::hidden('specialrequest', '', ['class' => 'form-control text-center  font-weight-bold','id'=>'requestValue']) }}
                                    <input type="hidden" id="requestTotal" class="SubTotal">
                                    <input type="hidden" id="counter" class="">
                                      <div>
                                          <span>Note!  </span>
                                      </div>
                                  
                                    <div class="custom-checkbox">
                                        <div class="row text-bold pl-4">
                                            <div class="col-6 ">
                                                Name
                                            </div>
                                            <div class="col-6">
                                               Price
                                            </div>
                                        </div>
                                        @foreach ($guestRequest as $request)
                                            <div class="form-check">
                                                <div class="row">
                                                    <div class="col-6">
                                                         <label>
                                                            <input type="checkbox" name="request" id="guestRequest" class="request" :data-price="{{ $request->price }}" value="{{ $request->name }}"> <span class="label-text"> {{ $request->name  }} </span> 
                                                        </label>
                                                    </div>
                                                    <div class="col-6">
                                                        <span class="text-success"> ₱{{ $request->price }}</span>
                                                    </div>
                                                </div>
                                               
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                                
                                <input type="checkbox" name="" id="terms"> I hereby agree to the <button type="button"  data-toggle="modal" data-target="#TermsAndConditionModal">Terms and Condition</a> 
                                <br>
                                <div class="w-100 ">
                                   
                                </div>
                
              </div>
           
            <div class="text-right mt-3">
              <button type="button" class="btn btn-success p-3 BookNow  w-100" disabled ><i class="fab fa-paypal fa-2x"></i> <span class="mx-auto">aid </span>  <span id="totalToPaid" class="text-bold"></span> Php</button>
            </div>
            
        </form>
          </div>
       
         
        </div>
 
    </div>
  </div>
  
<!-- Modal -->
<div class="modal fade" id="TermsAndConditionModal" tabindex="-1" role="dialog" aria-labelledby="TermsAndConditionModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered " role="document">
    <div class="modal-content bg-info">    
      <div class="modal-body text-center">
          <h1 class="text-center">Terms and Condition </h1><hr>
          50% downpayment, 50% full payment upon arrival<br>
          No refund

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn text-white acceptTerm bg-success" data-dismiss="modal">Accept</button>
      </div>
    </div>
  </div>
</div>

resources/views/modal/landingModal.blade.php
<div class="modal fade" id="Ardent-Hot-Spring" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row">
                    <div class="col-10">
                        <h5 class="modal-title" id="exampleModalLabel">Ardent Hot Spring</h5>
                    </div>
                    <div class="col-2">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-md-7 slickTourPackage-for mx-auto px-2">
                        <img src="{{asset('img/locale-attraction/ardent-hot-spring.jpg')}}" class="w-100" alt="">
                        <img src="{{asset('img/locale-attraction/ardent-hot-spring.jpg')}}" class="w-100" alt="">
                        <img src="{{asset('img/locale-attraction/ardent-hot-spring.jpg')}}" class="w-100" alt="">
                        
                    </div>
                 
                </div>
                <div class="row">
                <div class="col-md-7 slickTourPackage-nav mx-auto px-2">
                        <img src="{{asset('img/locale-attraction/ardent-hot-spring.jpg')}}" class="w-100" alt="">
                        <img src="{{asset('img/locale-attraction/ardent-hot-spring.jpg')}}" class="w-100" alt="">
                        <img src="{{asset('img/locale-attraction/ardent-hot-spring.jpg')}}" class="w-100" alt="">
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>